### ISSUE TITLE
No available subscription found in current account

### ISSUE THREAD

**Issue by florentbo** [Azure-Samples/hello-spring-function-azure#16]
Hi,
I followed this tutorial step by step.
Package goal was OK.
Run goal was OK.
But I encountered a problem during the deploy, I received the following error:
No available subscription found in current account

The only way to solve it was to solve it was by following this documentation:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/error-register-resource-provider

and to add a registration 
az provider register --namespace 'microsoft.insights'
Where to find that stuff in the readme or in a documentation?

**Comment by jdubois** [comment]
This is very strange, an account has to be in a subscription. It looks like the error message is a bit misleading, and that the real issue is that your account didn't have access to Azure Inisights - are you using a specific corporate account? Some of them have restrictions, and those depend on the company, so it's hard to tell.

**Comment by florentbo** [comment]
I have created an azure free account following that link:
https://azure.microsoft.com/en-us/free/
I used a gmail address to login. Re-try the same path than me and you will see ;)
As I told you, the az provider register --namespace 'microsoft.insights' command solved the problem, but it took me some times to try to understand what was the cause.
The 'microsoft.insights' is not mentioned in the doc

**Comment by jdubois** [comment]
Oh thanks - I’m currently working on what we offer as part of the free tier and maybe something was missed. I’ll have a look.

**Comment by jdubois** [comment]
@florentbo I have discussed this with @jeffhollan and he created this specific ticket to track your issue, which is likely caused by our Maven plugin: https://github.com/microsoft/azure-maven-plugins/issues/1101

**Comment by florentbo** [comment]
https://github.com/Azure-Samples/hello-spring-function-azure/pull/22 solved the issue
