### ISSUE TITLE
EventHubTrigger not working with Spring Cloud

### ISSUE THREAD

**Issue by DhivyaDhivosh** [Azure-Samples/hello-spring-function-azure#17]
I’am working on integrating the Azure EventHubTrigger Function with Spring Cloud Functions. I followed the below link which explains how HttpTrigger Function delegates the request to Spring Cloud. https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure When I try the same with EventHubTrigger, I get “Exception: IllegalStateException: No function defined”. Below is the screenshot of the log.

![image](https://user-images.githubusercontent.com/53916455/86017987-5b17e580-b9ea-11ea-8974-a650e1bd4448.png)
![image](https://user-images.githubusercontent.com/53916455/86018020-6539e400-b9ea-11ea-9b61-eb343339972e.png)
![image](https://user-images.githubusercontent.com/53916455/86018085-784cb400-b9ea-11ea-8866-8a378e93848d.png)

**Comment by jdubois** [comment]
It's hard to tell as I'm not using this at all in this sample (this is why I'm closing this).
But it looks like a usual bug we had here: please use the latest version of the Maven plugin, and be sure to add the `<start-class>com.example.HelloFunction</start-class>` property in your `pom.xml`. It's one of the different ways to make Azure Function knows where your function is (there are 2 other ways to do it, so if it doesn't work please add a comment).

**Comment by DhivyaDhivosh** [comment]
Iam using <start-class>org.iot.enrichment.EventFunction</start-class> which specifies the MainFunction.

**Comment by jdubois** [comment]
Then I'm sorry because I don't know this at all. I'm only using the HTTP trigger in this sample.

**Comment by DhivyaDhivosh** [comment]
Also, When I run this code using terminal it works well. The same code If I run using IntelliJ IDE it throws java.lang.IllegalStateException in exception in handleRequest method.

**Comment by jdubois** [comment]
I've only used the Maven plugin to run the code. I believe there is also an Intellij plugin, are you using this?

**Comment by DhivyaDhivosh** [comment]
Yes, I have installed Azure took kit plugin in Intellij which provide provision for using azure functions.

**Comment by jdubois** [comment]
Oh, in that case it's easy! First of all, I add back this property https://github.com/Azure-Samples/hello-spring-function-azure/commit/b72f1ce362517020dd28a77e20e6de5fbf9bb7d8 if you need to run this using the Maven plugin.
You need to set up the same property in your Azure Functions set screen, like in the screenshot below:
![Screenshot 2020-06-30 at 17 05 57](https://user-images.githubusercontent.com/316835/86142880-0365a100-baf4-11ea-9973-b87e46abb8c0.png)

**Comment by DhivyaDhivosh** [comment]
Hi, 

Whom I need to contact for integrating EventHubTrigger functionality with Spring cloud? This is very urgent.

**Comment by jdubois** [comment]
@DhivyaDhivosh let's discuss this on https://github.com/Azure-Samples/hello-spring-function-azure/issues/18 as you created another ticket for that
