### ISSUE TITLE
EventHubTrigger not working with Spring Cloud

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/hello-spring-function-azure#18]
I have been working on Integrating EventHubTrigger azure function with Spring cloud for the past one week. I have tried all the possible options and it keeps throwing 

**Exception: IllegalStateException: No function defined
Stack: java.lang.reflect.InvocationTargetException**

This is very urgent requirement that I am working on. Do you support only HttpTrigger at this point ? Please direct me to the right to check about the EventHubTrigger.

**Comment by jdubois** [comment]
I haven't used it personally, but there is another sample application for this, written by a colleague of mine: https://github.com/Azure-Samples/java-functions-eventhub-cosmosdb

**Comment by DhivyaDhivosh** [comment]
I have already tried that approach too. I still get the same "Illegal State Exception - No function defined".

**Comment by jdubois** [comment]
Maybe we can ask @KarlErickson as he is the one who build that application.

It looks like your function is not being found, usually you need to force its name using the "MAIN_CLASS" property, have you had a look at that? Like I do here: https://github.com/Azure-Samples/hello-spring-function-azure/blob/master/src/main/azure/local.settings.json

**Comment by DhivyaDhivosh** [comment]
I have my mainclass defined in Run configurations as well as in pom.xml file

**Comment by jdubois** [comment]
Do you have your error:

- When your function is deployed on Azure
- Running your function locally using the Maven plugin
- Running your function locally using the Intellij IDEA plugin

(of course you can select multiple answers!)

**Comment by DhivyaDhivosh** [comment]
Running your function locally using the Maven plugin

**Comment by jdubois** [comment]
It's really hard for me to understand what is wrong -> @DhivyaDhivosh could you share your project (privately) with me?

**Comment by rkralston** [comment]
Did you find a solution to this? I am trying to get get Blob Event to work and need some help configuring.

**Comment by rkralston** [comment]
The Azure sample you referenced above does not use the Spring Boot Function.

**Comment by jdubois** [comment]
Closing as I didn't have access to the project, and thus I couldn't test.
