### ISSUE TITLE
Project run doesn't works

### ISSUE THREAD

**Issue by antdiv** [Azure-Samples/hello-spring-function-azure#24]
I'm trying to run the project (maven version).
mvn package it's ok but when I try to run locally the command give me that:
C:\git_cloud\hello-spring-function-azure-master>mvnw.cmd azure-functions:run
Found "C:\git_cloud\hello-spring-function-azure-master\.mvn\wrapper\maven-wrapper.jar"
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------------< com.example:hello >--------------------------
[INFO] Building Hello Spring Function on Azure 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- azure-functions-maven-plugin:1.9.0:run (default-cli) @ hello ---
[WARNING] The POM for com.microsoft.azure.applicationinsights.v2015_05_01:azure-mgmt-insights:jar:1.0.0-beta is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] Azure Function App's staging directory found at: C:\git_cloud\hello-spring-function-azure-master\target\azure-functions\innovationfun

### Minimal steps to reproduce
- git clone
- config appname and resource name
- mvnw clean test
- mvnw package
- mvnw azure-function:un

**Comment by jdubois** [comment]
Well, with the following steps, it does run on my machine :-)
Do you have the Azure Functions Core Tools correctly installed on your machine? Do you have a stacktrace or something else?

**Comment by antdiv** [comment]
seems to be a problem with azure-functions msi ; solved with chocolatey
