### ISSUE TITLE
Use Mono in the samples

### ISSUE THREAD

**Issue by itsandreramon** [Azure-Samples/hello-spring-function-azure#26]
The sample uses Spring WebFlux, so the functions should return asynchronously using Mono<T>.

**Comment by jdubois** [comment]
And you are totally correct!!!!!
I migrated to Webflux recently and missed this.

**Comment by itsandreramon** [comment]
I also have this problem that the function completes before the Mono is completed. It works as expected when adding block(), but this seems like an anti-pattern to me:

![Screenshot 2021-03-12 at 23 57 12](https://user-images.githubusercontent.com/17139385/111007398-060cdb80-838f-11eb-997b-0644ce5d920f.png)
![Screenshot 2021-03-12 at 23 58 43](https://user-images.githubusercontent.com/17139385/111007394-04431800-838f-11eb-8620-f918b48e0a00.png)

**Comment by jdubois** [comment]
Indeed, you shouldn’t block - I don’t know how you configured Spring Data here, are you sure it’s reactive? Is it returning Mono/Flux?

**Comment by itsandreramon** [comment]
Im using ReactiveCrudRepository using MS SQL Driver connected to Azure and Cloud Function WebFlux. When using a Controller which returns Mono<T> it works as expected. Thanks for your help so far!

**Comment by jdubois** [comment]
Oh so it’s solved, great !
I’ll update this repo to use a Mono next week.

**Comment by itsandreramon** [comment]
Not really solved, because I wanna use the azure function and not the rest endpoint :/

**Comment by jdubois** [comment]
Migration to Mono is done and pushed, thanks a lot @itsandreramon !
