### ISSUE TITLE
Java azure function OS recommendation Linux vs Windows

### ISSUE THREAD

**Issue by Vipin-Sharma** [Azure-Samples/hello-spring-function-azure#30]
### This issue is for the [particular commit](https://github.com/Azure-Samples/hello-spring-function-azure/commit/96dcef04445002849f7e3fe0e022d499354e47fa#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8) message in this repo.

Java 11 is the latest LTS so it expected to perform better as it has several improvements over Java 8.
Can we say also Java azure functions perform better on Linux in comparison to Windows? that's the reason overall Linux + Java11 is the best combination for Java Azure functions.

This is a question, not a bug.

**Comment by jdubois** [comment]
Java 11 will indeed perform better than Java 8 in nearly every situation, and anyway it’s the current LTS so it’s you best choice.
For Linux vs Windows, I can’t give you an official answer as it depends on many things, and both platforms are continuously improved. So on a personal point of view, at the current time, yes Linux works much better.
